### PR TITLE
IDVA6-1299 - Welsh Translation - Add a Company

### PR DESCRIPTION
**Pull request by bwallace-ch**
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1299

Changes:
- Added Welsh translations for 'add company' page
- Updated 'continue' translation in common.json

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
