### PR TITLE
IDVA6-931 - matomo functionality for presenterAlreadyAuthorised page

### PR DESCRIPTION
**Pull request by bwallace-ch**
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-931

Changes:
- Added global 'Back Link' variable for matomo
- Added matomo tracking for back link and 'Back to Your Companies' link
- Updated back_link.njk to contain id for matomo tracking

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by mmodzelewski-ch — APPROVED** [review]

**Pull request merged**
