### PR TITLE
IDVA6-366 remove an authorised person page

### PR DESCRIPTION
**Pull request by bwallace-ch**
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-366

Changes:
- Remove authorised person page created
- Added query functionality for URLs
- Created unit tests for both page and query functionality

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by mmodzelewski-ch — DISMISSED** [review]

**Review by mmodzelewski-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by mmodzelewski-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
