### PR TITLE
IDVA6-1926 Web Security Node Upgrade

### PR DESCRIPTION
**Pull request by kwamenyantakyi-ch**
**JIRA link**
https://companieshouse.atlassian.net/browse/IDVA6-1926

**Description**
Updating **web security node** to 4.4.3 and **node session handler** to 5.2.0

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by mmodzelewski-ch — APPROVED** [review]

**Pull request merged**
