### PR TITLE
IDVA6-445 - Authorise User email sent success page

### PR DESCRIPTION
**Pull request by bmchugh-ch**
Link to Jira:

https://companieshouse.atlassian.net/browse/IDVA6-445

Changes:

auth person confirmation success banner and navigation logic
view templates moved into base folder and updates to contants.ts

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by mmodzelewski-ch — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by mmodzelewski-ch — APPROVED** [review]

**Pull request merged**
