### PR TITLE
IDVA6-1033 add goals to journeys

### PR DESCRIPTION
**Pull request by mmodzelewski-ch**
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1033

Changes:
- Goal tracking script added
- Goal tracking added to Add a company and Add new authorised person buttons added

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — DISMISSED** [review]

**Review by bmchugh-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
