### PR TITLE
IDVA6-802 your companies search error message

### PR DESCRIPTION
**Pull request by mmodzelewski-ch**
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-802

Changes:
- The hint text for a search input field updated.
- Search input validation and error messages added
- Unnecessary imports and unused variable removed

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — DISMISSED** [review]

**Review by kkonuganti-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — DISMISSED** [review]

**Review by bmchugh-ch — APPROVED** [review]

**Review by bmchugh-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — APPROVED** [review]

**Review by bmchugh-ch — DISMISSED** [review]

**Review by bmchugh-ch — DISMISSED** [review]

**Review by bmchugh-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by bmchugh-ch — APPROVED** [review]

**Pull request merged**
